monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.pci-0000_01_00.1"
      }
    ]
    actions = {
      update-props = {
        device.disabled = true
      }
    }
  }
  {
    matches = [
      {
        device.name = "alsa_card.usb-Sony_Interactive_Entertainment_Wireless_Controller-00"
      }
    ]
    actions = {
      update-props = {
        device.disabled = true
      }
    }
  }
]
